/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Modelo.Cliente;
import Modelo.Componentes;
import Modelo.ComponenteObj;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.GridBagConstraints;
import java.awt.GridLayout;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import GUI.Boton;
import Modelo.ActionListenerJuego;
import Modelo.IObjeto;
import Modelo.IdEnemigo;
import Modelo.Mensaje;
import Modelo.Status;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.IOException;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JLayeredPane;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 *
 * @author Paola Chinchilla
 */
public class Juego extends javax.swing.JFrame{

    /**
     * Creates new form Juego
     */
    private Cliente cliente;
    private Mercado ventMercado;
    private Boton[][] botones;
    private Boton[][] botonesEnemigo;
    private int filas = 20;
    private int columnas = 20;
    private ComponenteObj componenteActual;
    private int posXActual;
    private int posYActual;
    
    public Juego(Cliente cliente) {
        initComponents();
        this.cliente=cliente;
    }

    
    public void colocarCantidadesComponentes(){
        int cantidad;
        cantidad=cliente.getComponentesHashTable().get(Componentes.FUENTEENERGÍA);
        txt_FEnergia1.setText(Integer.toString(cantidad));
        
        cantidad=cliente.getComponentesHashTable().get(Componentes.CONECTOR);
        txt_Conector.setText(Integer.toString(cantidad));
        
        cantidad=cliente.getComponentesHashTable().get(Componentes.MERCADO);
        txt_Mercado.setText(Integer.toString(cantidad));
        
        cantidad=cliente.getComponentesHashTable().get(Componentes.MINA);
        txt_Mina.setText(Integer.toString(cantidad));
        
        cantidad=cliente.getComponentesHashTable().get(Componentes.TEMPLO);
        txt_Templo.setText(Integer.toString(cantidad));
        
        cantidad=cliente.getComponentesHashTable().get(Componentes.ACERO);
        txt_Acero.setText(Integer.toString(cantidad));
        
        cantidad=cliente.getComponentesHashTable().get(Componentes.BARCO);
        txt_Remolino.setText(Integer.toString(cantidad));
        
        cantidad=cliente.getComponentesHashTable().get(Componentes.BOMBA);
        txt_Bomba.setText(Integer.toString(cantidad));
        
        cantidad=cliente.getComponentesHashTable().get(Componentes.DINERO);
        txt_Dinero.setText(Integer.toString(cantidad));
        
        cantidad=cliente.getComponentesHashTable().get(Componentes.ARMERIA);
        txt_Fabrica.setText(Integer.toString(cantidad));
        
        cantidad=cliente.getComponentesHashTable().get(Componentes.MULTISHOT);
        txt_Multi.setText(Integer.toString(cantidad));
        
        cantidad=cliente.getComponentesHashTable().get(Componentes.REMOLINO);
        txt_Remolino.setText(Integer.toString(cantidad));
        
        cantidad=cliente.getComponentesHashTable().get(Componentes.TORPEDO);
        txt_Torpedo.setText(Integer.toString(cantidad));
        
        cantidad=cliente.getComponentesHashTable().get(Componentes.TRUMPEDO);
        txt_Trumpedo.setText(Integer.toString(cantidad));
    }

 
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        btnBomba = new javax.swing.JButton();
        btn_enemigo2 = new javax.swing.JButton();
        btn_enemigo3 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        btn_enemigo1 = new javax.swing.JButton();
        btn_Trumpedo = new javax.swing.JButton();
        remolinoButton = new javax.swing.JButton();
        btn_Torpedo = new javax.swing.JButton();
        btn_Multi = new javax.swing.JButton();
        txt_Torpedo = new javax.swing.JTextField();
        txt_Bomba = new javax.swing.JTextField();
        txt_Trumpedo = new javax.swing.JTextField();
        txt_Remolino = new javax.swing.JTextField();
        txt_Multi = new javax.swing.JTextField();
        btn_Conector = new javax.swing.JButton();
        btn_Mercado = new javax.swing.JButton();
        btn_Mina = new javax.swing.JButton();
        btn_Templo = new javax.swing.JButton();
        btn_FEnergia = new javax.swing.JButton();
        btn_Armeria = new javax.swing.JButton();
        txt_Fabrica = new javax.swing.JTextField();
        txt_Mercado = new javax.swing.JTextField();
        txt_Mina = new javax.swing.JTextField();
        txt_Templo = new javax.swing.JTextField();
        txt_Conector = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox();
        btn_Agregar = new javax.swing.JButton();
        btn_Disparar = new javax.swing.JButton();
        btn_Terminar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txt_Acero = new javax.swing.JTextField();
        txt_Dinero = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        iniciarButton = new javax.swing.JButton();
        btn_Barco = new javax.swing.JButton();
        txt_Barco2 = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        enemigoPanel = new javax.swing.JPanel();
        jugadorPanel = new javax.swing.JPanel();
        txt_FEnergia = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        txt_FEnergia1 = new javax.swing.JTextField();
        juegoPanel = new javax.swing.JPanel();

        jPanel2.setMaximumSize(new java.awt.Dimension(700, 700));

        jPanel2.setMinimumSize(new java.awt.Dimension(700, 700));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 460, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1200, 700));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 107, 53));
        jPanel1.setMaximumSize(new java.awt.Dimension(1784, 1000));
        jPanel1.setMinimumSize(new java.awt.Dimension(1784, 1000));
        jPanel1.setName(""); // NOI18N
        jPanel1.setLayout(null);

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(970, 510, 260, 190);

        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel1.add(jTextField1);
        jTextField1.setBounds(630, 600, 240, 30);

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel1.add(jButton1);
        jButton1.setBounds(880, 600, 70, 30);

        btnBomba.setBackground(new java.awt.Color(0, 0, 0));
        btnBomba.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnBomba.setForeground(new java.awt.Color(255, 255, 255));
        btnBomba.setText("Bomba");
        btnBomba.setToolTipText("");
        btnBomba.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBombaActionPerformed(evt);
            }
        });
        jPanel1.add(btnBomba);
        btnBomba.setBounds(490, 520, 100, 40);

        btn_enemigo2.setBackground(new java.awt.Color(0, 0, 0));
        btn_enemigo2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_enemigo2.setForeground(new java.awt.Color(255, 255, 255));
        btn_enemigo2.setText("J2");
        btn_enemigo2.setToolTipText("");
        btn_enemigo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_enemigo2ActionPerformed(evt);
            }
        });
        jPanel1.add(btn_enemigo2);
        btn_enemigo2.setBounds(1120, 120, 120, 40);

        btn_enemigo3.setBackground(new java.awt.Color(0, 0, 0));
        btn_enemigo3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_enemigo3.setForeground(new java.awt.Color(255, 255, 255));
        btn_enemigo3.setText("J3");
        btn_enemigo3.setToolTipText("");
        btn_enemigo3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_enemigo3ActionPerformed(evt);
            }
        });
        jPanel1.add(btn_enemigo3);
        btn_enemigo3.setBounds(1120, 180, 120, 40);

        jTextArea2.setColumns(20);
        jTextArea2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(630, 520, 320, 70);

        btn_enemigo1.setBackground(new java.awt.Color(0, 0, 0));
        btn_enemigo1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_enemigo1.setForeground(new java.awt.Color(255, 255, 255));
        btn_enemigo1.setText("J1");
        btn_enemigo1.setToolTipText("");
        btn_enemigo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_enemigo1ActionPerformed(evt);
            }
        });
        jPanel1.add(btn_enemigo1);
        btn_enemigo1.setBounds(1120, 60, 120, 40);

        btn_Trumpedo.setBackground(new java.awt.Color(0, 0, 0));
        btn_Trumpedo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_Trumpedo.setForeground(new java.awt.Color(255, 255, 255));
        btn_Trumpedo.setText("Trumpedo");
        btn_Trumpedo.setToolTipText("");
        btn_Trumpedo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_TrumpedoActionPerformed(evt);
            }
        });
        jPanel1.add(btn_Trumpedo);
        btn_Trumpedo.setBounds(270, 590, 100, 30);

        remolinoButton.setBackground(new java.awt.Color(0, 0, 0));
        remolinoButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        remolinoButton.setForeground(new java.awt.Color(255, 255, 255));
        remolinoButton.setText("Remolino");
        remolinoButton.setToolTipText("");
        remolinoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                remolinoButtonActionPerformed(evt);
            }
        });
        jPanel1.add(remolinoButton);
        remolinoButton.setBounds(490, 590, 100, 30);

        btn_Torpedo.setBackground(new java.awt.Color(0, 0, 0));
        btn_Torpedo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_Torpedo.setForeground(new java.awt.Color(255, 255, 255));
        btn_Torpedo.setText("Torpedo");
        btn_Torpedo.setToolTipText("");
        btn_Torpedo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_TorpedoActionPerformed(evt);
            }
        });
        jPanel1.add(btn_Torpedo);
        btn_Torpedo.setBounds(270, 520, 100, 40);

        btn_Multi.setBackground(new java.awt.Color(0, 0, 0));
        btn_Multi.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_Multi.setForeground(new java.awt.Color(255, 255, 255));
        btn_Multi.setText("Multi");
        btn_Multi.setToolTipText("");
        btn_Multi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_MultiActionPerformed(evt);
            }
        });
        jPanel1.add(btn_Multi);
        btn_Multi.setBounds(380, 520, 100, 40);

        txt_Torpedo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_Torpedo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txt_Torpedo);
        txt_Torpedo.setBounds(270, 560, 100, 21);

        txt_Bomba.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_Bomba.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txt_Bomba);
        txt_Bomba.setBounds(490, 560, 100, 21);

        txt_Trumpedo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_Trumpedo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txt_Trumpedo);
        txt_Trumpedo.setBounds(270, 630, 100, 21);

        txt_Remolino.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_Remolino.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txt_Remolino);
        txt_Remolino.setBounds(490, 630, 100, 21);

        txt_Multi.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_Multi.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txt_Multi);
        txt_Multi.setBounds(380, 560, 100, 21);

        btn_Conector.setBackground(new java.awt.Color(0, 0, 0));
        btn_Conector.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_Conector.setForeground(new java.awt.Color(255, 255, 255));
        btn_Conector.setText("Conector");
        btn_Conector.setToolTipText("");
        btn_Conector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ConectorActionPerformed(evt);
            }
        });
        jPanel1.add(btn_Conector);
        btn_Conector.setBounds(20, 130, 100, 40);

        btn_Mercado.setBackground(new java.awt.Color(0, 0, 0));
        btn_Mercado.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_Mercado.setForeground(new java.awt.Color(255, 255, 255));
        btn_Mercado.setText("Mercado");
        btn_Mercado.setToolTipText("");
        btn_Mercado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_MercadoActionPerformed(evt);
            }
        });
        jPanel1.add(btn_Mercado);
        btn_Mercado.setBounds(20, 230, 100, 40);

        btn_Mina.setBackground(new java.awt.Color(0, 0, 0));
        btn_Mina.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_Mina.setForeground(new java.awt.Color(255, 255, 255));
        btn_Mina.setText("Mina");
        btn_Mina.setToolTipText("");
        btn_Mina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_MinaActionPerformed(evt);
            }
        });
        jPanel1.add(btn_Mina);
        btn_Mina.setBounds(20, 310, 100, 40);

        btn_Templo.setBackground(new java.awt.Color(0, 0, 0));
        btn_Templo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_Templo.setForeground(new java.awt.Color(255, 255, 255));
        btn_Templo.setText("Templo");
        btn_Templo.setToolTipText("");
        btn_Templo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_TemploActionPerformed(evt);
            }
        });
        jPanel1.add(btn_Templo);
        btn_Templo.setBounds(20, 390, 100, 50);

        btn_FEnergia.setBackground(new java.awt.Color(0, 0, 0));
        btn_FEnergia.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_FEnergia.setForeground(new java.awt.Color(255, 255, 255));
        btn_FEnergia.setText("F. Energia");
        btn_FEnergia.setToolTipText("");
        btn_FEnergia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_FEnergiaActionPerformed(evt);
            }
        });
        jPanel1.add(btn_FEnergia);
        btn_FEnergia.setBounds(20, 30, 100, 50);

        btn_Armeria.setBackground(new java.awt.Color(0, 0, 0));
        btn_Armeria.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_Armeria.setForeground(new java.awt.Color(255, 255, 255));
        btn_Armeria.setText("Armería");
        btn_Armeria.setToolTipText("");
        btn_Armeria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ArmeriaActionPerformed(evt);
            }
        });
        jPanel1.add(btn_Armeria);
        btn_Armeria.setBounds(20, 510, 100, 50);

        txt_Fabrica.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_Fabrica.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txt_Fabrica);
        txt_Fabrica.setBounds(20, 570, 100, 21);

        txt_Mercado.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_Mercado.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txt_Mercado);
        txt_Mercado.setBounds(20, 280, 100, 21);

        txt_Mina.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_Mina.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txt_Mina);
        txt_Mina.setBounds(20, 360, 100, 21);

        txt_Templo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_Templo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txt_Templo);
        txt_Templo.setBounds(20, 450, 100, 21);

        txt_Conector.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_Conector.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txt_Conector);
        txt_Conector.setBounds(20, 190, 100, 21);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Torpedo", "Multi", "Bomba", "Trumpedo" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox1);
        jComboBox1.setBounds(20, 480, 100, 20);

        btn_Agregar.setBackground(new java.awt.Color(0, 0, 0));
        btn_Agregar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_Agregar.setForeground(new java.awt.Color(255, 255, 255));
        btn_Agregar.setText("Agregar");
        btn_Agregar.setToolTipText("");
        btn_Agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AgregarActionPerformed(evt);
            }
        });
        jPanel1.add(btn_Agregar);
        btn_Agregar.setBounds(20, 600, 100, 25);

        btn_Disparar.setBackground(new java.awt.Color(0, 0, 0));
        btn_Disparar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_Disparar.setForeground(new java.awt.Color(255, 255, 255));
        btn_Disparar.setText("Disparar");
        btn_Disparar.setToolTipText("");
        btn_Disparar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_DispararActionPerformed(evt);
            }
        });
        jPanel1.add(btn_Disparar);
        btn_Disparar.setBounds(150, 520, 100, 25);

        btn_Terminar.setBackground(new java.awt.Color(0, 0, 0));
        btn_Terminar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_Terminar.setForeground(new java.awt.Color(255, 255, 255));
        btn_Terminar.setText("Terminar");
        btn_Terminar.setToolTipText("");
        jPanel1.add(btn_Terminar);
        btn_Terminar.setBounds(150, 550, 100, 25);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Acero");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(160, 630, 70, 30);

        txt_Acero.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_Acero.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txt_Acero);
        txt_Acero.setBounds(140, 660, 100, 21);

        txt_Dinero.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_Dinero.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txt_Dinero);
        txt_Dinero.setBounds(20, 660, 100, 21);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Dinero");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(40, 630, 70, 30);

        iniciarButton.setText("INICIAR");
        jPanel1.add(iniciarButton);
        iniciarButton.setBounds(660, 640, 80, 60);

        btn_Barco.setBackground(new java.awt.Color(0, 0, 0));
        btn_Barco.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_Barco.setForeground(new java.awt.Color(255, 255, 255));
        btn_Barco.setText("Barco");
        btn_Barco.setToolTipText("");
        btn_Barco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_BarcoActionPerformed(evt);
            }
        });
        jPanel1.add(btn_Barco);
        btn_Barco.setBounds(380, 590, 100, 30);

        txt_Barco2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_Barco2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txt_Barco2);
        txt_Barco2.setBounds(380, 630, 100, 21);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        enemigoPanel.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout enemigoPanelLayout = new javax.swing.GroupLayout(enemigoPanel);
        enemigoPanel.setLayout(enemigoPanelLayout);
        enemigoPanelLayout.setHorizontalGroup(
            enemigoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 460, Short.MAX_VALUE)
        );
        enemigoPanelLayout.setVerticalGroup(
            enemigoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 460, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 460, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(enemigoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 460, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(enemigoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jPanel1.add(jPanel3);
        jPanel3.setBounds(640, 30, 460, 460);

        jugadorPanel.setBackground(new java.awt.Color(255, 255, 255));
        jugadorPanel.setLayout(null);

        txt_FEnergia.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_FEnergia.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jugadorPanel.add(txt_FEnergia);
        txt_FEnergia.setBounds(-30, 10, 30, 21);

        jTextArea3.setColumns(20);
        jTextArea3.setRows(5);
        jScrollPane4.setViewportView(jTextArea3);

        jugadorPanel.add(jScrollPane4);
        jScrollPane4.setBounds(40, 20, 70, 40);

        jPanel1.add(jugadorPanel);
        jugadorPanel.setBounds(160, 30, 460, 460);

        jLayeredPane1.setLayout(new java.awt.GridBagLayout());
        jPanel1.add(jLayeredPane1);
        jLayeredPane1.setBounds(590, 20, 100, 100);

        txt_FEnergia1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_FEnergia1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_FEnergia1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_FEnergia1ActionPerformed(evt);
            }
        });
        jPanel1.add(txt_FEnergia1);
        txt_FEnergia1.setBounds(20, 90, 100, 21);

        juegoPanel.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout juegoPanelLayout = new javax.swing.GroupLayout(juegoPanel);
        juegoPanel.setLayout(juegoPanelLayout);
        juegoPanelLayout.setHorizontalGroup(
            juegoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 460, Short.MAX_VALUE)
        );
        juegoPanelLayout.setVerticalGroup(
            juegoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 450, Short.MAX_VALUE)
        );

        jPanel1.add(juegoPanel);
        juegoPanel.setBounds(160, 40, 460, 450);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1248, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 10, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 713, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 9, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void btn_AgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AgregarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_AgregarActionPerformed

    private void btn_DispararActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_DispararActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_DispararActionPerformed

    private void btn_MercadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_MercadoActionPerformed
        this.ventMercado = new Mercado(this.cliente);
        ventMercado.setVisible(true);
        colocarCantidadesComponentes();
    }//GEN-LAST:event_btn_MercadoActionPerformed

    private void btn_FEnergiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_FEnergiaActionPerformed
        int x=this.getPosXActual();
        int y=this.getPosYActual();
        Componentes componente= Componentes.FUENTEENERGÍA;
        posicionarComponente(componente,x,y);
        
    }//GEN-LAST:event_btn_FEnergiaActionPerformed

                    
    private void btn_ConectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ConectorActionPerformed
        int x=this.getPosXActual();
        int y=this.getPosYActual();
        Componentes componente= Componentes.CONECTOR;
        posicionarComponente(componente,x,y);
    }//GEN-LAST:event_btn_ConectorActionPerformed

    private void btn_MinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_MinaActionPerformed
        int x=this.getPosXActual();
        int y=this.getPosYActual();
        Componentes componente= Componentes.MINA;
        posicionarComponente(componente,x,y);
    }//GEN-LAST:event_btn_MinaActionPerformed

    private void btn_TemploActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_TemploActionPerformed
        int x=this.getPosXActual();
        int y=this.getPosYActual();
        Componentes componente= Componentes.TEMPLO;
        posicionarComponente(componente,x,y);
    }//GEN-LAST:event_btn_TemploActionPerformed

    private void btn_ArmeriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ArmeriaActionPerformed
        int x=this.getPosXActual();
        int y=this.getPosYActual();
        Componentes componente= Componentes.ARMERIA;
        posicionarComponente(componente,x,y);
    }//GEN-LAST:event_btn_ArmeriaActionPerformed

    private void btn_TorpedoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_TorpedoActionPerformed
        int x=this.getPosXActual();
        int y=this.getPosYActual();
        Componentes componente= Componentes.TORPEDO;
        posicionarComponente(componente,x,y);
    }//GEN-LAST:event_btn_TorpedoActionPerformed

    private void btn_MultiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_MultiActionPerformed
        int x=this.getPosXActual();
        int y=this.getPosYActual();
        Componentes componente= Componentes.MULTISHOT;
        posicionarComponente(componente,x,y);
    }//GEN-LAST:event_btn_MultiActionPerformed

    private void btnBombaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBombaActionPerformed
        int x=this.getPosXActual();
        int y=this.getPosYActual();
        Componentes componente= Componentes.BOMBA;
        posicionarComponente(componente,x,y);
    }//GEN-LAST:event_btnBombaActionPerformed

    private void btn_TrumpedoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_TrumpedoActionPerformed
        int x=this.getPosXActual();
        int y=this.getPosYActual();
        Componentes componente= Componentes.TRUMPEDO;
        posicionarComponente(componente,x,y);
    }//GEN-LAST:event_btn_TrumpedoActionPerformed

    private void btn_BarcoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_BarcoActionPerformed
        int x=this.getPosXActual();
        int y=this.getPosYActual();
        Componentes componente= Componentes.BARCO;
        posicionarComponente(componente,x,y);
    }//GEN-LAST:event_btn_BarcoActionPerformed

    private void remolinoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_remolinoButtonActionPerformed
        int x=this.getPosXActual();
        int y=this.getPosYActual();
        Componentes componente= Componentes.REMOLINO;
        posicionarComponente(componente,x,y);
    }//GEN-LAST:event_remolinoButtonActionPerformed

    private void txt_FEnergia1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_FEnergia1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_FEnergia1ActionPerformed

    private void btn_enemigo3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_enemigo3ActionPerformed
       IdEnemigo enemigo= getEnemigoArray(2);
       clearEnemigoPanel();
       posicionarComponentesEnemigo(enemigo);
    }//GEN-LAST:event_btn_enemigo3ActionPerformed

    private void btn_enemigo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_enemigo1ActionPerformed
       IdEnemigo enemigo= getEnemigoArray(0);
       clearEnemigoPanel();
       posicionarComponentesEnemigo(enemigo);
       
    }//GEN-LAST:event_btn_enemigo1ActionPerformed

    private void btn_enemigo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_enemigo2ActionPerformed
       IdEnemigo enemigo= getEnemigoArray(1);
       clearEnemigoPanel();
       posicionarComponentesEnemigo(enemigo);
    }//GEN-LAST:event_btn_enemigo2ActionPerformed
    
    public String getImagenComponente(Componentes componente){
        String imagen = "";
        switch(componente){
            case FUENTEENERGÍA:
               imagen="src/Imagenes/Fuente.png"; 
               break;
            case MINA:
               imagen="src/Imagenes/mineria2.png"; 
               break;
            case CONECTOR:
               imagen="src/Imagenes/enlace.png"; 
               break;
            case TEMPLO:
               imagen="src/Imagenes/escudo.png"; 
               break;
            case BARCO:
               imagen="src/Imagenes/barco.png"; 
               break;   
            case REMOLINO:
               imagen="src/Imagenes/remolino.png"; 
               break;
            case ARMERIA:
               imagen="src/Imagenes/robots.png"; 
               break;
            
        }
        return imagen;
    }
    
    public void reducirInventario(Componentes componente){
        int cantActual=cliente.getComponentesHashTable().get(componente);
        cliente.getComponentesHashTable().replace(
                    componente,cantActual-1);
    }
    public boolean hayDisponible(Componentes componente){
        int disponible=cliente.getComponentesHashTable().get(componente);
        if(disponible>0){
            return true;
        }
        else return false;
    }
    
    public void setLabel(int i,int j,String tipo,JPanel panel){
        
         botones[i][j].setText(tipo);
         JButton label=botones[i][j];
         panel.add(label);
         
        
    }
    
    public void limpiarTablero(){
        for(int i=0; i<filas;i++){
            for(int j=0; j<columnas;j++){
                botones[i][j].setText("    ");
            }
        }
    }
    public void setMatrizGrafica(){
       	
        //Eliminamos los anteriores botones
        jugadorPanel.removeAll();
        jugadorPanel.setBackground( new Color(254,254,254));
        enemigoPanel.removeAll();
        enemigoPanel.setBackground( new Color(254,254,254));

        //Se crea una matriz de botones segun las filas y columnas entrantes
       
        botones = new Boton[ filas ][ columnas ];
        botonesEnemigo = new Boton[ filas ][ columnas ];
        
        //Se recorren las filas
        for( int fila = 0 ; fila < filas; fila++ )
        {
            //Estando en la fila se recorrer las columnas
            for( int columna = 0 ; columna < columnas; columna++ )
            {
                //Se crea el boton y se agrega a las celda de la matriz
                botones[fila][columna] = new Boton( 23*columna,23* fila, 25, 25 );
                
                //Se da el nombre en forma de coordenada enviando la fila y columna
                botones[fila][columna].setNombre("");
                botones[fila][columna].setBackground(new Color(30,158,195));
                //Agregar action listener
                botones[fila][columna].addActionListener(new ActionListenerJuego(
                this,fila,columna,botones[fila][columna]));
                
               
                //Se agrega el boton al panel
                jugadorPanel.add(botones[fila][columna] );  
            }
        }
        
        //Se actualiza el panel para que se vean los botones
	jugadorPanel.updateUI();
        for( int fila = 0 ; fila < filas; fila++ )
        {
            //Estando en la fila se recorrer las columnas
            for( int columna = 0 ; columna < columnas; columna++ )
            {
                //Se crea el boton y se agrega a las celda de la matriz
                botonesEnemigo[fila][columna] = new Boton( 23*columna,23* fila, 25, 25 );
                
                //Se da el nombre en forma de coordenada enviando la fila y columna
                botonesEnemigo[fila][columna].setNombre("");
                botonesEnemigo[fila][columna].setBackground(new Color(0,61,91));
                
                //Se agrega el boton al panel
          
                enemigoPanel.add(botonesEnemigo[fila][columna] );
            }
        }
        enemigoPanel.updateUI();
        
    } 
    
    public void clearEnemigoPanel(){
        for( int fila = 0 ; fila < filas; fila++ )
        {
            //Estando en la fila se recorrer las columnas
            for( int columna = 0 ; columna < columnas; columna++ )
            {
                //Se crea el boton y se agrega a las celda de la matriz
                
                //Se da el nombre en forma de coordenada enviando la fila y columna
                botonesEnemigo[fila][columna].setIcon(null);
            }
        }
        enemigoPanel.updateUI();
    }
    
    public void clearPanel(String panelNombre, JPanel panel){
        Boton[][] botonesPanel=null;
        if(panelNombre=="jugadorPanel"){
            botonesPanel=botones;
        }
        else if(panelNombre=="enemigoPanel"){
            botonesPanel=botonesEnemigo;
        }
        
        for( int fila = 0 ; fila < filas; fila++ )
        {
            for( int columna = 0 ; columna < columnas; columna++ )
            {
               
                
                //Se da el nombre en forma de coordenada enviando la fila y columna
                botonesPanel[fila][columna].setNombre("");
                setImage(fila,columna," ",panel,panelNombre);
                botonesPanel[fila][columna].setBackground(new Color(0,61,91));
                
                //Se agrega el boton al panel
          
                panel.add(botones[fila][columna] );
            }
        }
        panel.updateUI();
        
    }
        
    public ImageIcon getIconoNuevos (String string){

        ImageIcon imagen = new javax.swing.ImageIcon(string);        
        ImageIcon img = new ImageIcon(imagen.getImage().getScaledInstance(34, 34, 34));
        return img;
    }
    public void setImage(int i,int j,String string, JPanel panel,String nombrePanel){
        ImageIcon imagen;
        if (string=="Vacia"){
             imagen=new ImageIcon();
         }
         imagen= new ImageIcon(string);
         imagen= new ImageIcon(imagen.getImage().getScaledInstance(34, 34, 34));
         JButton boton = null;
         System.out.println("NOMBRE DEL PANEL: "+panel.getName());
         if(nombrePanel=="jugadorPanel"){
            botones[i][j].setIcon(imagen);
            boton=botones[i][j];
            jugadorPanel.add(boton);
         }
         else if(nombrePanel=="enemigoPanel"){
            System.out.println("Es enemigo panel");
            botonesEnemigo[i][j].setIcon(imagen);
            boton=botonesEnemigo[i][j];
            System.out.println("Encontró boton:"+boton);
            //boton.setVisible(true);
            enemigoPanel.add(boton);
            enemigoPanel.repaint();
         }
         //panel.add(boton);
         //panel.updateUI();
         
    }
    
    public void posicionarComponente(Componentes componente,int x, int y){
        componenteActual= cliente.getFabricaComponentes().crearComponente(componente);
        componenteActual.setPosX(x);
        componenteActual.setPosY(y);
        componenteActual.setIdDuenno(cliente.getIdJugador());
        String imagen= getImagenComponente(componente);
        if(hayDisponible(componente)){
            cliente.getGrafo().setPosTableroLogico(x, y, componenteActual);
            setImage(x,y,imagen,jugadorPanel,"jugadorPanel");
            reducirInventario(componente);  
            colocarCantidadesComponentes();
            if(componenteActual.getTipo()==Componentes.FUENTEENERGÍA){
                cliente.clientThread.sendPackage(componenteActual);
            }
        }
        else componenteActual=null;
    }
    
    public void posicionarComponentesEnemigo(IdEnemigo enemigo){
        
       ArrayList<ComponenteObj> componentesEnemigo=
               cliente.clientThread.getEnemigosHashTable().get(enemigo);
       String imagen;
       int x;
       int y;
       //clearPanel(enemigoPanel);
       System.out.println("componente recibido:"+componentesEnemigo.get(0).getTipo());
       for(ComponenteObj componente: componentesEnemigo){
            imagen= getImagenComponente(componente.getTipo());
            x=componente.getPosX();
            y=componente.getPosY();
            setImage(x,y,imagen,enemigoPanel,"enemigoPanel");
       }
    }
    
    public void actualizarJugadoresID(){
        this.setTitle("Jugador "+cliente.getIdJugador());

        btn_enemigo1.setText("Jugador "+getNumEnemigoArray(0));
        System.out.println("Tamaño:"+cliente.getClientThread().getEnemigos().size());
        if(cliente.getClientThread().getEnemigos().size()>1){
           btn_enemigo2.setText("Jugador "+getNumEnemigoArray(1)); 
           btn_enemigo2.setVisible(true);
        }
        else{
           btn_enemigo2.setVisible(false);
        }
        if(cliente.getClientThread().getEnemigos().size()>2){
           btn_enemigo3.setText("Jugador "+getNumEnemigoArray(2)); 
           btn_enemigo3.setVisible(true);
        }
        else{
            btn_enemigo3.setVisible(false);
        }
        
    }
    public int getNumEnemigoArray(int i){
        return cliente.getClientThread().getEnemigos().get(i).getNumEnemigo();
    }
    public IdEnemigo getEnemigoArray(int i){
        return cliente.getClientThread().getEnemigos().get(i);
    }

    public Cliente getCliente() {
        return cliente;
    }

    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }

    public Mercado getVentMercado() {
        return ventMercado;
    }

    public void setVentMercado(Mercado ventMercado) {
        this.ventMercado = ventMercado;
    }

    public Boton[][] getBotones() {
        return botones;
    }

    public void setBotones(Boton[][] botones) {
        this.botones = botones;
    }


    public int getFilas() {
        return filas;
    }

    public void setFilas(int filas) {
        this.filas = filas;
    }

    public int getColumnas() {
        return columnas;
    }

    public void setColumnas(int columnas) {
        this.columnas = columnas;
    }

    public JButton getBtnBomba() {
        return btnBomba;
    }

    public void setBtnBomba(JButton btnBomba) {
        this.btnBomba = btnBomba;
    }

    public ComponenteObj getComponenteActual() {
        return componenteActual;
    }

    public void setComponenteActual(ComponenteObj componenteActual) {
        this.componenteActual = componenteActual;
    }

    public JButton getBtn_Agregar() {
        return btn_Agregar;
    }

    public void setBtn_Agregar(JButton btn_Agregar) {
        this.btn_Agregar = btn_Agregar;
    }

    public JButton getBtn_Barco() {
        return btn_Barco;
    }

    public void setBtn_Barco(JButton btn_Barco) {
        this.btn_Barco = btn_Barco;
    }

    public JButton getBtn_Conector() {
        return btn_Conector;
    }

    public void setBtn_Conector(JButton btn_Conector) {
        this.btn_Conector = btn_Conector;
    }

    public JButton getBtn_Disparar() {
        return btn_Disparar;
    }

    public void setBtn_Disparar(JButton btn_Disparar) {
        this.btn_Disparar = btn_Disparar;
    }

    public JButton getBtn_FEnergia() {
        return btn_FEnergia;
    }

    public void setBtn_FEnergia(JButton btn_FEnergia) {
        this.btn_FEnergia = btn_FEnergia;
    }

    public JButton getBtn_Fabrica() {
        return btn_Armeria;
    }

    public void setBtn_Fabrica(JButton btn_Fabrica) {
        this.btn_Armeria = btn_Fabrica;
    }

    public JButton getBtn_J2() {
        return btn_enemigo2;
    }

    public void setBtn_J2(JButton btn_J2) {
        this.btn_enemigo2 = btn_J2;
    }

    public JButton getBtn_J3() {
        return btn_enemigo3;
    }

    public void setBtn_J3(JButton btn_J3) {
        this.btn_enemigo3 = btn_J3;
    }


    public JButton getBtn_J5() {
        return btn_enemigo1;
    }

    public void setBtn_J5(JButton btn_J5) {
        this.btn_enemigo1 = btn_J5;
    }

    public JButton getBtn_Mercado() {
        return btn_Mercado;
    }

    public void setBtn_Mercado(JButton btn_Mercado) {
        this.btn_Mercado = btn_Mercado;
    }

    public JButton getBtn_Mina() {
        return btn_Mina;
    }

    public void setBtn_Mina(JButton btn_Mina) {
        this.btn_Mina = btn_Mina;
    }

    public JButton getBtn_Multi() {
        return btn_Multi;
    }

    public void setBtn_Multi(JButton btn_Multi) {
        this.btn_Multi = btn_Multi;
    }

    public JButton getBtn_Templo() {
        return btn_Templo;
    }

    public void setBtn_Templo(JButton btn_Templo) {
        this.btn_Templo = btn_Templo;
    }

    public JButton getBtn_Terminar() {
        return btn_Terminar;
    }

    public void setBtn_Terminar(JButton btn_Terminar) {
        this.btn_Terminar = btn_Terminar;
    }

    public JButton getBtn_Torpedo() {
        return btn_Torpedo;
    }

    public void setBtn_Torpedo(JButton btn_Torpedo) {
        this.btn_Torpedo = btn_Torpedo;
    }

    public JButton getBtn_Trumpedo() {
        return btn_Trumpedo;
    }

    public void setBtn_Trumpedo(JButton btn_Trumpedo) {
        this.btn_Trumpedo = btn_Trumpedo;
    }

    public JPanel getEnemigoPanel() {
        return enemigoPanel;
    }

    public void setEnemigoPanel(JPanel enemigoPanel) {
        this.enemigoPanel = enemigoPanel;
    }

    public JButton getIniciarButton() {
        return iniciarButton;
    }

    public void setIniciarButton(JButton iniciarButton) {
        this.iniciarButton = iniciarButton;
    }

    public JButton getjButton1() {
        return jButton1;
    }

    public void setjButton1(JButton jButton1) {
        this.jButton1 = jButton1;
    }

    public JComboBox getjComboBox1() {
        return jComboBox1;
    }

    public void setjComboBox1(JComboBox jComboBox1) {
        this.jComboBox1 = jComboBox1;
    }

    public JLabel getjLabel3() {
        return jLabel3;
    }

    public void setjLabel3(JLabel jLabel3) {
        this.jLabel3 = jLabel3;
    }

    public JLabel getjLabel5() {
        return jLabel5;
    }

    public void setjLabel5(JLabel jLabel5) {
        this.jLabel5 = jLabel5;
    }

    public JLayeredPane getjLayeredPane1() {
        return jLayeredPane1;
    }

    public void setjLayeredPane1(JLayeredPane jLayeredPane1) {
        this.jLayeredPane1 = jLayeredPane1;
    }

    public JPanel getjPanel1() {
        return jPanel1;
    }

    public void setjPanel1(JPanel jPanel1) {
        this.jPanel1 = jPanel1;
    }

    public JPanel getjPanel2() {
        return jPanel2;
    }

    public void setjPanel2(JPanel jPanel2) {
        this.jPanel2 = jPanel2;
    }

    public JPanel getjPanel3() {
        return jPanel3;
    }

    public void setjPanel3(JPanel jPanel3) {
        this.jPanel3 = jPanel3;
    }

    public JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    public void setjScrollPane1(JScrollPane jScrollPane1) {
        this.jScrollPane1 = jScrollPane1;
    }

    public JScrollPane getjScrollPane2() {
        return jScrollPane2;
    }

    public void setjScrollPane2(JScrollPane jScrollPane2) {
        this.jScrollPane2 = jScrollPane2;
    }

    public JScrollPane getjScrollPane4() {
        return jScrollPane4;
    }

    public void setjScrollPane4(JScrollPane jScrollPane4) {
        this.jScrollPane4 = jScrollPane4;
    }

    public JTextArea getjTextArea1() {
        return jTextArea1;
    }

    public Boton[][] getBotonesEnemigo() {
        return botonesEnemigo;
    }

    public void setBotonesEnemigo(Boton[][] botonesEnemigo) {
        this.botonesEnemigo = botonesEnemigo;
    }

    public void setjTextArea1(JTextArea jTextArea1) {
        this.jTextArea1 = jTextArea1;
    }

    public JTextArea getjTextArea2() {
        return jTextArea2;
    }

    public void setjTextArea2(JTextArea jTextArea2) {
        this.jTextArea2 = jTextArea2;
    }

    public JTextArea getjTextArea3() {
        return jTextArea3;
    }

    public void setjTextArea3(JTextArea jTextArea3) {
        this.jTextArea3 = jTextArea3;
    }

    public JTextField getjTextField1() {
        return jTextField1;
    }

    public void setjTextField1(JTextField jTextField1) {
        this.jTextField1 = jTextField1;
    }

    public JPanel getJuegoPanel() {
        return juegoPanel;
    }

    public void setJuegoPanel(JPanel juegoPanel) {
        this.juegoPanel = juegoPanel;
    }

    public JPanel getJugadorPanel() {
        return jugadorPanel;
    }

    public void setJugadorPanel(JPanel jugadorPanel) {
        this.jugadorPanel = jugadorPanel;
    }

    public JButton getRemolinoButton() {
        return remolinoButton;
    }

    public void setRemolinoButton(JButton remolinoButton) {
        this.remolinoButton = remolinoButton;
    }

    public JTextField getTxt_Acero() {
        return txt_Acero;
    }

    public void setTxt_Acero(JTextField txt_Acero) {
        this.txt_Acero = txt_Acero;
    }

    public JTextField getTxt_Barco2() {
        return txt_Barco2;
    }

    public void setTxt_Barco2(JTextField txt_Barco2) {
        this.txt_Barco2 = txt_Barco2;
    }

    public JTextField getTxt_Bomba() {
        return txt_Bomba;
    }

    public void setTxt_Bomba(JTextField txt_Bomba) {
        this.txt_Bomba = txt_Bomba;
    }

    public JTextField getTxt_Conector() {
        return txt_Conector;
    }

    public void setTxt_Conector(JTextField txt_Conector) {
        this.txt_Conector = txt_Conector;
    }

    public JTextField getTxt_Dinero() {
        return txt_Dinero;
    }

    public void setTxt_Dinero(JTextField txt_Dinero) {
        this.txt_Dinero = txt_Dinero;
    }

    public JTextField getTxt_FEnergia() {
        return txt_FEnergia;
    }

    public void setTxt_FEnergia(JTextField txt_FEnergia) {
        this.txt_FEnergia = txt_FEnergia;
    }

    public JTextField getTxt_FEnergia1() {
        return txt_FEnergia1;
    }

    public void setTxt_FEnergia1(JTextField txt_FEnergia1) {
        this.txt_FEnergia1 = txt_FEnergia1;
    }

    public JTextField getTxt_Fabrica() {
        return txt_Fabrica;
    }

    public void setTxt_Fabrica(JTextField txt_Fabrica) {
        this.txt_Fabrica = txt_Fabrica;
    }

    public JTextField getTxt_Mercado() {
        return txt_Mercado;
    }

    public void setTxt_Mercado(JTextField txt_Mercado) {
        this.txt_Mercado = txt_Mercado;
    }

    public JTextField getTxt_Mina() {
        return txt_Mina;
    }

    public void setTxt_Mina(JTextField txt_Mina) {
        this.txt_Mina = txt_Mina;
    }

    public JTextField getTxt_Multi() {
        return txt_Multi;
    }

    public void setTxt_Multi(JTextField txt_Multi) {
        this.txt_Multi = txt_Multi;
    }

    public JTextField getTxt_Remolino() {
        return txt_Remolino;
    }

    public void setTxt_Remolino(JTextField txt_Remolino) {
        this.txt_Remolino = txt_Remolino;
    }

    public JTextField getTxt_Templo() {
        return txt_Templo;
    }

    public void setTxt_Templo(JTextField txt_Templo) {
        this.txt_Templo = txt_Templo;
    }

    public JTextField getTxt_Torpedo() {
        return txt_Torpedo;
    }

    public int getPosXActual() {
        return posXActual;
    }

    public void setPosXActual(int posXActual) {
        this.posXActual = posXActual;
    }

    public int getPosYActual() {
        return posYActual;
    }

    public void setPosYActual(int posYActual) {
        this.posYActual = posYActual;
    }
    
    public void setTxt_Torpedo(JTextField txt_Torpedo) {
        this.txt_Torpedo = txt_Torpedo;
    }

    public JTextField getTxt_Trumpedo() {
        return txt_Trumpedo;
    }

    public void setTxt_Trumpedo(JTextField txt_Trumpedo) {
        this.txt_Trumpedo = txt_Trumpedo;
    }
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Juego juego= new Juego(new Cliente());
                juego.setVisible(true);
                juego.setMatrizGrafica();
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBomba;
    private javax.swing.JButton btn_Agregar;
    private javax.swing.JButton btn_Armeria;
    private javax.swing.JButton btn_Barco;
    private javax.swing.JButton btn_Conector;
    private javax.swing.JButton btn_Disparar;
    private javax.swing.JButton btn_FEnergia;
    private javax.swing.JButton btn_Mercado;
    private javax.swing.JButton btn_Mina;
    private javax.swing.JButton btn_Multi;
    private javax.swing.JButton btn_Templo;
    private javax.swing.JButton btn_Terminar;
    private javax.swing.JButton btn_Torpedo;
    private javax.swing.JButton btn_Trumpedo;
    private javax.swing.JButton btn_enemigo1;
    private javax.swing.JButton btn_enemigo2;
    private javax.swing.JButton btn_enemigo3;
    private javax.swing.JPanel enemigoPanel;
    private javax.swing.JButton iniciarButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JPanel juegoPanel;
    private javax.swing.JPanel jugadorPanel;
    private javax.swing.JButton remolinoButton;
    private javax.swing.JTextField txt_Acero;
    private javax.swing.JTextField txt_Barco2;
    private javax.swing.JTextField txt_Bomba;
    private javax.swing.JTextField txt_Conector;
    private javax.swing.JTextField txt_Dinero;
    private javax.swing.JTextField txt_FEnergia;
    private javax.swing.JTextField txt_FEnergia1;
    private javax.swing.JTextField txt_Fabrica;
    private javax.swing.JTextField txt_Mercado;
    private javax.swing.JTextField txt_Mina;
    private javax.swing.JTextField txt_Multi;
    private javax.swing.JTextField txt_Remolino;
    private javax.swing.JTextField txt_Templo;
    private javax.swing.JTextField txt_Torpedo;
    private javax.swing.JTextField txt_Trumpedo;
    // End of variables declaration//GEN-END:variables
}
