/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Modelo.Cliente;
import Modelo.Componentes;
import battleship.Componente;
import java.awt.Color;

/**
 *
 * @author Paola Chinchilla
 */
public class Mercado extends javax.swing.JFrame {

    /**
     * Creates new form Mercado
     */
    Cliente cliente;
    private String componenteActual;
    private int precio;
    private int cantidad;
    private String destino;
    private boolean destinoJugador=false;
    private int dineroDisponible;
    private int aceroDisponible;
    private boolean pagaConAcero=false;
    private Componentes enumComponenteActual;
    
    
    public Mercado(Cliente cliente) {
        this.cliente=cliente;
        initComponents();
        actualizarDineroAcero();
        setDefaultCloseOperation(Mercado.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        btn_FEnergia = new javax.swing.JButton();
        btn_Vender = new javax.swing.JButton();
        btn_Mercado = new javax.swing.JButton();
        btn_Mina = new javax.swing.JButton();
        btn_Armeria = new javax.swing.JButton();
        btn_Torpedo = new javax.swing.JButton();
        btn_Trumpedo = new javax.swing.JButton();
        btn_Multi = new javax.swing.JButton();
        btn_Jugador4 = new javax.swing.JButton();
        btn_Barco = new javax.swing.JButton();
        btn_Mercado1 = new javax.swing.JButton();
        btn_Bomba = new javax.swing.JButton();
        btn_Jugador1 = new javax.swing.JButton();
        btn_Jugador2 = new javax.swing.JButton();
        btn_Jugador3 = new javax.swing.JButton();
        btn_Conector = new javax.swing.JButton();
        btn_Comprar = new javax.swing.JButton();
        dineroDisponibleTField = new javax.swing.JTextField();
        destinoTField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        totalTField = new javax.swing.JTextField();
        cantidadTField = new javax.swing.JTextField();
        cantidadMenosBoton = new javax.swing.JButton();
        cantidadMasBoton = new javax.swing.JButton();
        btn_Templo = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        componenteTField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        aceroDisponibleTField = new javax.swing.JTextField();
        precioTField = new javax.swing.JTextField();
        infoTField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Transacción con:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(450, 210, 170, 40);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Cantidad:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(450, 300, 90, 40);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Total:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(450, 380, 90, 40);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Mercado");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(30, 10, 170, 30);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Desde/Hacia:");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(450, 70, 130, 40);

        btn_FEnergia.setBackground(new java.awt.Color(153, 102, 255));
        btn_FEnergia.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_FEnergia.setForeground(new java.awt.Color(255, 255, 255));
        btn_FEnergia.setText("F. Energia");
        btn_FEnergia.setToolTipText("");
        btn_FEnergia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_FEnergiaActionPerformed(evt);
            }
        });
        jPanel1.add(btn_FEnergia);
        btn_FEnergia.setBounds(100, 120, 100, 40);

        btn_Vender.setBackground(new java.awt.Color(102, 255, 255));
        btn_Vender.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_Vender.setForeground(new java.awt.Color(255, 255, 255));
        btn_Vender.setText("Vender");
        btn_Vender.setToolTipText("");
        btn_Vender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_VenderActionPerformed(evt);
            }
        });
        jPanel1.add(btn_Vender);
        btn_Vender.setBounds(670, 530, 120, 80);

        btn_Mercado.setBackground(new java.awt.Color(153, 102, 255));
        btn_Mercado.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_Mercado.setForeground(new java.awt.Color(255, 255, 255));
        btn_Mercado.setText("Mercado");
        btn_Mercado.setToolTipText("");
        btn_Mercado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_MercadoActionPerformed(evt);
            }
        });
        jPanel1.add(btn_Mercado);
        btn_Mercado.setBounds(590, 70, 100, 40);

        btn_Mina.setBackground(new java.awt.Color(153, 102, 255));
        btn_Mina.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_Mina.setForeground(new java.awt.Color(255, 255, 255));
        btn_Mina.setText("Mina");
        btn_Mina.setToolTipText("");
        btn_Mina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_MinaActionPerformed(evt);
            }
        });
        jPanel1.add(btn_Mina);
        btn_Mina.setBounds(100, 280, 100, 40);

        btn_Armeria.setBackground(new java.awt.Color(153, 102, 255));
        btn_Armeria.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_Armeria.setForeground(new java.awt.Color(255, 255, 255));
        btn_Armeria.setText("Armeria");
        btn_Armeria.setToolTipText("");
        btn_Armeria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ArmeriaActionPerformed(evt);
            }
        });
        jPanel1.add(btn_Armeria);
        btn_Armeria.setBounds(100, 400, 100, 40);

        btn_Torpedo.setBackground(new java.awt.Color(0, 0, 0));
        btn_Torpedo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_Torpedo.setForeground(new java.awt.Color(255, 255, 255));
        btn_Torpedo.setText("Torpedo");
        btn_Torpedo.setToolTipText("");
        btn_Torpedo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_TorpedoActionPerformed(evt);
            }
        });
        jPanel1.add(btn_Torpedo);
        btn_Torpedo.setBounds(230, 150, 100, 30);

        btn_Trumpedo.setBackground(new java.awt.Color(0, 0, 0));
        btn_Trumpedo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_Trumpedo.setForeground(new java.awt.Color(255, 255, 255));
        btn_Trumpedo.setText("Trumpedo");
        btn_Trumpedo.setToolTipText("");
        btn_Trumpedo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_TrumpedoActionPerformed(evt);
            }
        });
        jPanel1.add(btn_Trumpedo);
        btn_Trumpedo.setBounds(230, 310, 100, 40);

        btn_Multi.setBackground(new java.awt.Color(0, 0, 0));
        btn_Multi.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_Multi.setForeground(new java.awt.Color(255, 255, 255));
        btn_Multi.setText("Multi");
        btn_Multi.setToolTipText("");
        btn_Multi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_MultiActionPerformed(evt);
            }
        });
        jPanel1.add(btn_Multi);
        btn_Multi.setBounds(230, 190, 100, 40);

        btn_Jugador4.setBackground(new java.awt.Color(0, 0, 0));
        btn_Jugador4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_Jugador4.setForeground(new java.awt.Color(255, 255, 255));
        btn_Jugador4.setText("Jugador 4");
        btn_Jugador4.setToolTipText("");
        btn_Jugador4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Jugador4ActionPerformed(evt);
            }
        });
        jPanel1.add(btn_Jugador4);
        btn_Jugador4.setBounds(810, 120, 100, 40);

        btn_Barco.setBackground(new java.awt.Color(0, 0, 0));
        btn_Barco.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_Barco.setForeground(new java.awt.Color(255, 255, 255));
        btn_Barco.setText("Barco");
        btn_Barco.setToolTipText("");
        btn_Barco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_BarcoActionPerformed(evt);
            }
        });
        jPanel1.add(btn_Barco);
        btn_Barco.setBounds(230, 370, 100, 40);

        btn_Mercado1.setBackground(new java.awt.Color(153, 102, 255));
        btn_Mercado1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_Mercado1.setForeground(new java.awt.Color(255, 255, 255));
        btn_Mercado1.setText("Mercado");
        btn_Mercado1.setToolTipText("");
        btn_Mercado1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Mercado1ActionPerformed(evt);
            }
        });
        jPanel1.add(btn_Mercado1);
        btn_Mercado1.setBounds(100, 220, 100, 40);

        btn_Bomba.setBackground(new java.awt.Color(0, 0, 0));
        btn_Bomba.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_Bomba.setForeground(new java.awt.Color(255, 255, 255));
        btn_Bomba.setText("Bomba");
        btn_Bomba.setToolTipText("");
        btn_Bomba.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_BombaActionPerformed(evt);
            }
        });
        jPanel1.add(btn_Bomba);
        btn_Bomba.setBounds(230, 250, 100, 40);

        btn_Jugador1.setBackground(new java.awt.Color(0, 0, 0));
        btn_Jugador1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_Jugador1.setForeground(new java.awt.Color(255, 255, 255));
        btn_Jugador1.setText("Jugador 1");
        btn_Jugador1.setToolTipText("");
        btn_Jugador1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Jugador1ActionPerformed(evt);
            }
        });
        jPanel1.add(btn_Jugador1);
        btn_Jugador1.setBounds(700, 70, 100, 40);

        btn_Jugador2.setBackground(new java.awt.Color(0, 0, 0));
        btn_Jugador2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_Jugador2.setForeground(new java.awt.Color(255, 255, 255));
        btn_Jugador2.setText("Jugador 2");
        btn_Jugador2.setToolTipText("");
        btn_Jugador2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Jugador2ActionPerformed(evt);
            }
        });
        jPanel1.add(btn_Jugador2);
        btn_Jugador2.setBounds(810, 70, 100, 40);

        btn_Jugador3.setBackground(new java.awt.Color(0, 0, 0));
        btn_Jugador3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_Jugador3.setForeground(new java.awt.Color(255, 255, 255));
        btn_Jugador3.setText("Jugador 3");
        btn_Jugador3.setToolTipText("");
        btn_Jugador3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Jugador3ActionPerformed(evt);
            }
        });
        jPanel1.add(btn_Jugador3);
        btn_Jugador3.setBounds(700, 120, 100, 40);

        btn_Conector.setBackground(new java.awt.Color(153, 102, 255));
        btn_Conector.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_Conector.setForeground(new java.awt.Color(255, 255, 255));
        btn_Conector.setText("Conector");
        btn_Conector.setToolTipText("");
        btn_Conector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ConectorActionPerformed(evt);
            }
        });
        jPanel1.add(btn_Conector);
        btn_Conector.setBounds(100, 170, 100, 40);

        btn_Comprar.setBackground(new java.awt.Color(51, 255, 204));
        btn_Comprar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_Comprar.setForeground(new java.awt.Color(255, 255, 255));
        btn_Comprar.setText("Comprar");
        btn_Comprar.setToolTipText("");
        btn_Comprar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ComprarActionPerformed(evt);
            }
        });
        jPanel1.add(btn_Comprar);
        btn_Comprar.setBounds(520, 530, 120, 80);

        dineroDisponibleTField.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        dineroDisponibleTField.setForeground(new java.awt.Color(0, 51, 204));
        dineroDisponibleTField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dineroDisponibleTFieldActionPerformed(evt);
            }
        });
        jPanel1.add(dineroDisponibleTField);
        dineroDisponibleTField.setBounds(90, 520, 100, 30);

        destinoTField.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        destinoTField.setForeground(new java.awt.Color(0, 51, 204));
        destinoTField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                destinoTFieldActionPerformed(evt);
            }
        });
        jPanel1.add(destinoTField);
        destinoTField.setBounds(610, 220, 130, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Dinero");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(90, 480, 90, 40);

        totalTField.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        totalTField.setForeground(new java.awt.Color(0, 51, 204));
        totalTField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalTFieldActionPerformed(evt);
            }
        });
        jPanel1.add(totalTField);
        totalTField.setBounds(610, 390, 100, 30);

        cantidadTField.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        cantidadTField.setForeground(new java.awt.Color(0, 51, 204));
        cantidadTField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cantidadTFieldActionPerformed(evt);
            }
        });
        jPanel1.add(cantidadTField);
        cantidadTField.setBounds(610, 300, 100, 30);

        cantidadMenosBoton.setBackground(new java.awt.Color(255, 102, 102));
        cantidadMenosBoton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cantidadMenosBoton.setText("-");
        cantidadMenosBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cantidadMenosBotonActionPerformed(evt);
            }
        });
        jPanel1.add(cantidadMenosBoton);
        cantidadMenosBoton.setBounds(780, 300, 50, 30);

        cantidadMasBoton.setBackground(new java.awt.Color(102, 255, 102));
        cantidadMasBoton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cantidadMasBoton.setText("+");
        cantidadMasBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cantidadMasBotonActionPerformed(evt);
            }
        });
        jPanel1.add(cantidadMasBoton);
        cantidadMasBoton.setBounds(720, 300, 50, 30);

        btn_Templo.setBackground(new java.awt.Color(153, 102, 255));
        btn_Templo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_Templo.setForeground(new java.awt.Color(255, 255, 255));
        btn_Templo.setText("Templo");
        btn_Templo.setToolTipText("");
        btn_Templo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_TemploActionPerformed(evt);
            }
        });
        jPanel1.add(btn_Templo);
        btn_Templo.setBounds(100, 340, 100, 40);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Componente:");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(450, 250, 130, 40);

        componenteTField.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        componenteTField.setForeground(new java.awt.Color(0, 51, 204));
        componenteTField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                componenteTFieldActionPerformed(evt);
            }
        });
        jPanel1.add(componenteTField);
        componenteTField.setBounds(610, 260, 130, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Acero");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(240, 480, 90, 40);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Precio:");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(450, 340, 90, 40);

        aceroDisponibleTField.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        aceroDisponibleTField.setForeground(new java.awt.Color(0, 51, 204));
        aceroDisponibleTField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aceroDisponibleTFieldActionPerformed(evt);
            }
        });
        jPanel1.add(aceroDisponibleTField);
        aceroDisponibleTField.setBounds(240, 520, 100, 30);

        precioTField.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        precioTField.setForeground(new java.awt.Color(0, 51, 204));
        precioTField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                precioTFieldActionPerformed(evt);
            }
        });
        jPanel1.add(precioTField);
        precioTField.setBounds(610, 350, 100, 30);

        infoTField.setBackground(new java.awt.Color(51, 153, 255));
        infoTField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        infoTField.setForeground(new java.awt.Color(255, 255, 255));
        infoTField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                infoTFieldActionPerformed(evt);
            }
        });
        jPanel1.add(infoTField);
        infoTField.setBounds(520, 470, 280, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/battleship.jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, -30, 1000, 670);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1001, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 635, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_FEnergiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_FEnergiaActionPerformed
       componenteActual= "Fuente de Energía";
       pagaConAcero=false;
       Componentes componente= Componentes.FUENTEENERGÍA;
       enumComponenteActual=Componentes.FUENTEENERGÍA;
       actualizarDatos(componente,componenteActual);
    }//GEN-LAST:event_btn_FEnergiaActionPerformed

    private void dineroDisponibleTFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dineroDisponibleTFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dineroDisponibleTFieldActionPerformed

    private void destinoTFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_destinoTFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_destinoTFieldActionPerformed

    private void totalTFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalTFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalTFieldActionPerformed

    private void cantidadTFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cantidadTFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cantidadTFieldActionPerformed

    private void cantidadMenosBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cantidadMenosBotonActionPerformed
       cantidad--;
       cantidadTField.setText(Integer.toString(cantidad));
       actualizarTotalDinero(cantidad);
    }//GEN-LAST:event_cantidadMenosBotonActionPerformed

    private void cantidadMasBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cantidadMasBotonActionPerformed
       cantidad++;
       cantidadTField.setText(Integer.toString(cantidad));
       actualizarTotalDinero(cantidad);
    }//GEN-LAST:event_cantidadMasBotonActionPerformed

    private void btn_ConectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ConectorActionPerformed
       componenteActual= "Conector";
       pagaConAcero=false;
       Componentes componente= Componentes.CONECTOR;
       enumComponenteActual=Componentes.CONECTOR;
       actualizarDatos(componente,componenteActual);
    }//GEN-LAST:event_btn_ConectorActionPerformed

    private void btn_Mercado1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Mercado1ActionPerformed
       componenteActual= "Mercado";
       pagaConAcero=false;
       Componentes componente= Componentes.MERCADO;
       enumComponenteActual=Componentes.MERCADO;
       actualizarDatos(componente,componenteActual);
    }//GEN-LAST:event_btn_Mercado1ActionPerformed

    private void btn_MinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_MinaActionPerformed
       componenteActual= "Mina";
       pagaConAcero=false;
       Componentes componente= Componentes.MINA;
       enumComponenteActual=Componentes.MINA;
       actualizarDatos(componente,componenteActual);
    }//GEN-LAST:event_btn_MinaActionPerformed

    private void btn_TemploActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_TemploActionPerformed
       componenteActual= "Templo";
       pagaConAcero=false;
       Componentes componente= Componentes.TEMPLO;
       enumComponenteActual=Componentes.TEMPLO;
       actualizarDatos(componente,componenteActual);
    }//GEN-LAST:event_btn_TemploActionPerformed

    private void btn_ArmeriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ArmeriaActionPerformed
       componenteActual= "Armeria";
       pagaConAcero=false;
       Componentes componente= Componentes.ARMERIA;
       enumComponenteActual=Componentes.ARMERIA;
       actualizarDatos(componente,componenteActual);
    }//GEN-LAST:event_btn_ArmeriaActionPerformed

    private void btn_TorpedoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_TorpedoActionPerformed
       componenteActual= "Torpedo";
       Componentes componente= Componentes.TORPEDO;
       enumComponenteActual=Componentes.TORPEDO;
       pagaConAcero=true;
       actualizarDatos(componente,componenteActual);
       
    }//GEN-LAST:event_btn_TorpedoActionPerformed

    private void btn_MultiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_MultiActionPerformed
       componenteActual= "Multi Shot";
       pagaConAcero=true;
       Componentes componente= Componentes.MULTISHOT;
       enumComponenteActual=Componentes.MULTISHOT;
       actualizarDatos(componente,componenteActual);
    }//GEN-LAST:event_btn_MultiActionPerformed

    private void btn_BombaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_BombaActionPerformed
      componenteActual= "Bomba";
      pagaConAcero=true;
      Componentes componente= Componentes.BOMBA;
      enumComponenteActual=Componentes.BOMBA;
      actualizarDatos(componente,componenteActual);
    }//GEN-LAST:event_btn_BombaActionPerformed

    private void btn_TrumpedoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_TrumpedoActionPerformed
      componenteActual= "Trumpedo";
      pagaConAcero=true;
      Componentes componente= Componentes.TRUMPEDO;
      enumComponenteActual=Componentes.TRUMPEDO;
      actualizarDatos(componente,componenteActual);
    }//GEN-LAST:event_btn_TrumpedoActionPerformed

    private void btn_BarcoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_BarcoActionPerformed
      componenteActual= "Barco";
      pagaConAcero=true;
      Componentes componente= Componentes.BARCO;
      enumComponenteActual=Componentes.BARCO;
      actualizarDatos(componente,componenteActual);
    }//GEN-LAST:event_btn_BarcoActionPerformed

    private void componenteTFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_componenteTFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_componenteTFieldActionPerformed

    private void btn_MercadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_MercadoActionPerformed
        destino= "Mercado";
        destinoJugador=false;
        destinoTField.setText(destino);
    }//GEN-LAST:event_btn_MercadoActionPerformed

    private void btn_Jugador1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Jugador1ActionPerformed
        destino= "Jugador 1";
        destinoJugador=true;
        destinoTField.setText(destino);
    }//GEN-LAST:event_btn_Jugador1ActionPerformed

    private void btn_Jugador2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Jugador2ActionPerformed
        destino= "Jugador 2";
        destinoJugador=true;
        destinoTField.setText(destino);
    }//GEN-LAST:event_btn_Jugador2ActionPerformed

    private void btn_Jugador3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Jugador3ActionPerformed
        destino= "Jugador 3";
        destinoJugador=true;
        destinoTField.setText(destino);
    }//GEN-LAST:event_btn_Jugador3ActionPerformed

    private void btn_Jugador4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Jugador4ActionPerformed
        destino= "Jugador 4";
        destinoJugador=true;
        destinoTField.setText(destino);
    }//GEN-LAST:event_btn_Jugador4ActionPerformed

    private void aceroDisponibleTFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aceroDisponibleTFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aceroDisponibleTFieldActionPerformed

    private void precioTFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_precioTFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_precioTFieldActionPerformed

    private void btn_ComprarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ComprarActionPerformed
       int totalPagar= Integer.parseInt(totalTField.getText());
       int cantidadComprar= Integer.parseInt(cantidadTField.getText());
       int disponible;
       Componentes tipoPago;
       Componentes componente= enumComponenteActual;

       int cantidadActualStock=cliente.getComponentesHashTable().get(componente);
       
       if(!pagaConAcero){
           disponible=cliente.getComponentesHashTable().get(Componentes.DINERO);
           tipoPago= Componentes.DINERO;
           
       }
       else{
           disponible=cliente.getComponentesHashTable().get(Componentes.ACERO);
           tipoPago=Componentes.ACERO;
       }
       
       if(disponible>=totalPagar){
           //Actualiza BD del cliente
           cantidadActualStock= cantidadActualStock+cantidadComprar;
           System.out.println("Disponible antes:"+disponible);
           System.out.println("TotalPagar:"+totalPagar);
           disponible= disponible-totalPagar;
           System.out.println("Disponible nuevo:"+disponible);
           cliente.getComponentesHashTable().replace(
                   componente, cantidadActualStock);
           cliente.getComponentesHashTable().replace(
                   tipoPago, disponible ); 
           System.out.println("Disponible:"+cliente.getComponentesHashTable().get(Componentes.DINERO));
           System.out.println("Disponible:"+cliente.getComponentesHashTable().get(Componentes.ARMERIA));
           infoTField.setBackground(new Color(67,204,94));
           infoTField.setText("Compra exitosa");
           actualizarDineroAcero();
           cliente.getJuego().colocarCantidadesComponentes();
       }
       else{
           infoTField.setBackground(new Color(219,58,52));
           infoTField.setText("No tiene recursos sufiecientes");
           actualizarDineroAcero();
       }
       
    }//GEN-LAST:event_btn_ComprarActionPerformed

    private void infoTFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_infoTFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_infoTFieldActionPerformed

    private void btn_VenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_VenderActionPerformed
       int totalPagar= Integer.parseInt(totalTField.getText());
       int cantidadVender= Integer.parseInt(cantidadTField.getText());
       int disponible;
       Componentes tipoPago;
       Componentes componente= enumComponenteActual;

       int cantidadActualStock=cliente.getComponentesHashTable().get(componente);
       
       if(!pagaConAcero){
           disponible=cliente.getComponentesHashTable().get(Componentes.DINERO);
           tipoPago= Componentes.DINERO;   
       }
       else{
           disponible=cliente.getComponentesHashTable().get(Componentes.ACERO);
           tipoPago=Componentes.ACERO;
       }
       
       if(cantidadActualStock>=cantidadVender){
           //Actualiza BD del cliente
           cantidadActualStock= cantidadActualStock-cantidadVender;
           disponible= disponible+totalPagar;
           cliente.getComponentesHashTable().replace(
                   componente, cantidadActualStock);
           cliente.getComponentesHashTable().replace(
                   tipoPago, (disponible)); 
           
           infoTField.setBackground(new Color(67,204,94));
           infoTField.setText("Venta exitosa");
           actualizarDineroAcero();
       }
       else{
           infoTField.setBackground(new Color(219,58,52));
           infoTField.setText("No tiene componentes suficientes");
           actualizarDineroAcero();
       }
    }//GEN-LAST:event_btn_VenderActionPerformed

    public String getComponenteActual() {
        return componenteActual;
    }

    public void setComponenteActual(String componenteActual) {
        this.componenteActual = componenteActual;
    }
    
  
    public void actualizarDatos(Componentes componente, String componenteActual){
       precio= cliente.getComponentInfo(componente).getPrecio();
       cantidad=1;
       componenteTField.setText(componenteActual);
       precioTField.setText(Integer.toString(precio));
       cantidadTField.setText(Integer.toString(cantidad));
       actualizarTotalDinero(cantidad);
    }
    
    public void actualizarTotalDinero(int cantidad){
        int precioA= Integer.parseInt(precioTField.getText());
        int total= precioA*cantidad;
        totalTField.setText(Integer.toString(total));
        
    }
    
    public void actualizarDineroAcero(){
        dineroDisponible= cliente.getComponentesHashTable().get(Componentes.DINERO);
        aceroDisponible= cliente.getComponentesHashTable().get(Componentes.ACERO);
        dineroDisponibleTField.setText(Integer.toString(dineroDisponible));
        aceroDisponibleTField.setText(Integer.toString(aceroDisponible));
    }

    public String getDestino() {
        return destino;
    }

    public void setDestino(String destino) {
        this.destino = destino;
    }

    public boolean isDestinoJugador() {
        return destinoJugador;
    }

    public void setDestinoJugador(boolean destinoJugador) {
        this.destinoJugador = destinoJugador;
    }
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Mercado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Mercado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Mercado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Mercado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Mercado(new Cliente()).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField aceroDisponibleTField;
    private javax.swing.JButton btn_Armeria;
    private javax.swing.JButton btn_Barco;
    private javax.swing.JButton btn_Bomba;
    private javax.swing.JButton btn_Comprar;
    private javax.swing.JButton btn_Conector;
    private javax.swing.JButton btn_FEnergia;
    private javax.swing.JButton btn_Jugador1;
    private javax.swing.JButton btn_Jugador2;
    private javax.swing.JButton btn_Jugador3;
    private javax.swing.JButton btn_Jugador4;
    private javax.swing.JButton btn_Mercado;
    private javax.swing.JButton btn_Mercado1;
    private javax.swing.JButton btn_Mina;
    private javax.swing.JButton btn_Multi;
    private javax.swing.JButton btn_Templo;
    private javax.swing.JButton btn_Torpedo;
    private javax.swing.JButton btn_Trumpedo;
    private javax.swing.JButton btn_Vender;
    private javax.swing.JButton cantidadMasBoton;
    private javax.swing.JButton cantidadMenosBoton;
    private javax.swing.JTextField cantidadTField;
    private javax.swing.JTextField componenteTField;
    private javax.swing.JTextField destinoTField;
    private javax.swing.JTextField dineroDisponibleTField;
    private javax.swing.JTextField infoTField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField precioTField;
    private javax.swing.JTextField totalTField;
    // End of variables declaration//GEN-END:variables
}
